print("Ivesti du skaičius:")
print("Pirmas skaičius:")
a = int(input())
print("Antras skaičius:")
b = int(input())
print("Suma:", a + b)

print("Ivesti du skaičius:")
print("Pirmas skaičius:")
a = int(input())
print("Antras skaičius:")
b = int(input())
print("Atimtis:", a - b)
