print("Ivesti du skaičius:")
print("Pirmas skaičius:")
a = int(input())
print("Antras skaičius:")
b = int(input())
print("Sudėtis:", a + b)

print("Ivesti du skaičius:")
print("Pirmas skaičius:")
a = int(input())
print("Antras skaičius:")
b = int(input())
print("Atimtis:", a - b)

print("Ivesti du skaičius:")
print("Pirmas skaičius:")
a = int(input())
print("Antras skaičius:")
b = int(input())
print("Daugyba:", a * b)

print("Ivesti du skaičius:")
print("Pirmas skaičius:")
a = int(input())
print("Antras skaičius:")
b = int(input())
print("Dalyba:", a / b)

print('Hello, world!')
